language: node_js
node_js:
            - "0.8"
            - "0.10"
            - "0.12"
            - "1.0"
            - "1.8"
            - "2.0"
before_install:
            -"npm install"
            -"grunt concat"
script: mocha-phantomjs test/index.html