language: node_js
node_js:
            - "0.10"
            - "0.12"
            - "1.0"
            - "1.8"
            - "2.0"
script: mocha-phantomjs -A "firefox" -s webSecurityEnabled=false test/index.html